dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

# Can be reactived when this issue will be resolved: https://github.com/cospired/i18n-iso-languages/issues/17
#cache:
#  directories:
#    - ./node_modules

install:
  - npm install

script:
  - ./run-tests.sh
