name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: install package
      run: |
        npm install -g @angular/cli@19
        npm ci
    - name: run tests
      run: |
        ./run-tests.sh

      env:
        CI: true
