name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 24
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: install package
      run: |
        npm install -g @angular/cli@21
        npm ci
    - name: run tests
      run: |
        ./run-tests.sh

      env:
        CI: true
