name: GPR publication
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@rero-test'
      - name: GIT setup
        run: |
          git config --global user.email "<software@rero.ch>"
          git config --global user.name "RERO"
      - run: npm ci
      - run: npm version prerelease --preid=$(cut -c1-7 <<< $GITHUB_SHA) --allow-same-version
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
